name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&`#@'
no-changes-template: '- No user-facing changes'

categories:
  - title: 'Rules'
    labels:
      - 'area:rules'
    semver-increment: minor
  - title: 'Config Presets'
    labels:
      - 'area:configs'
      - 'area:plugin'
    semver-increment: minor
  - title: 'Fixes'
    labels:
      - 'type:fix'
      - 'bug'
    semver-increment: patch
  - title: 'Documentation'
    labels:
      - 'area:docs'
      - 'type:docs'
  - title: 'Tests and CI'
    labels:
      - 'area:tests'
      - 'area:ci'
      - 'area:package'
  - type: 'pre-exclude'
    when:
      label: 'skip-changelog'
  - type: 'version-resolver'
    semver-increment: 'patch'

sort-by: 'merged_at'
sort-direction: 'descending'
template: |
  ## Changes

  $CHANGES
